server:
  port: 8081

spring:
  application:
    name: scrapper
  grpc:
    client:
      channels:
        bot:
          address: localhost:9090
    server:
      port: 9091

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: file:migrations/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

app:
  stackoverflow:
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}

  github:
    token: ${GITHUB_TOKEN}

  bot:
    url: http://localhost:8080

  scheduler:
    interval: 60s # polling
    batch-size: 100

logging:
  structured:
    format:
      console: ecs
