server:
  port: 8080

spring:
  application:
    name: bot
  output:
    ansi:
      enabled: always
  grpc:
    server:
      port: 9090
    client:
      channels:
        scrapper:
          address: localhost:9091

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bot-consumer-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: backend.academy.linktracker.bot.dto.LinkUpdate

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${APP_TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false

logging:
  structured:
    format:
      console: ecs
  level:
    root: WARN
    backend.academy.linktracker: WARN
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.testcontainers: WARN
    org.apache.kafka.common.metrics: WARN
